homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 0
  longitude: 0
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Istanbul
  customize: !include customize.yaml
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
# Enables configuration UI
config:

system_health:

cloud:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  #base_url: home.kaynak.io:8123
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

influxdb:
  host: influxdb

recorder:
  purge_interval: 2
  purge_keep_days: 7
  db_url: postgresql://hass:hasspass@postredb/homeassistant
# Cloud
cloud:

recorder:
  purge_interval: 2
  purge_keep_days: 7
  db_url: postgresql://hass:hasspass@postredb/homeassistant

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr
    name: Weather
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature
  - platform: time_date
    display_options:
      #- 'time'
      #- 'date'
      - "date_time"
      #- 'time_date'
      #- 'time_utc'
      #- 'beat'
tts:
  platform: google

mqtt:
  broker: mqtt
  client_id: home-assistant
  protocol: 3.1
  username: "mqttuser"
  password: "mqttpassword"